update=Saturday, February 03, 2018 'PMt' 02:26:34 PM
version=1
last_client=kicad
[pcbnew]
version=1
LastNetListRead=
UseCmpFile=1
PadDrill=0.600000000000
PadDrillOvalY=0.600000000000
PadSizeH=1.500000000000
PadSizeV=1.500000000000
PcbTextSizeV=1.500000000000
PcbTextSizeH=1.500000000000
PcbTextThickness=0.300000000000
ModuleTextSizeV=1.000000000000
ModuleTextSizeH=1.000000000000
ModuleTextSizeThickness=0.150000000000
SolderMaskClearance=0.000000000000
SolderMaskMinWidth=0.000000000000
DrawSegmentWidth=0.200000000000
BoardOutlineThickness=0.100000000000
ModuleOutlineThickness=0.150000000000
[cvpcb]
version=1
NetIExt=net
[general]
version=1
[eeschema]
version=1
LibDir=
[eeschema/libraries]
LibName1=power
LibName2=device
LibName3=transistors
LibName4=conn
LibName5=linear
LibName6=regul
LibName7=74xx
LibName8=cmos4000
LibName9=adc-dac
LibName10=memory
LibName11=xilinx
LibName12=microcontrollers
LibName13=dsp
LibName14=microchip
LibName15=analog_switches
LibName16=motorola
LibName17=texas
LibName18=intel
LibName19=audio
LibName20=interface
LibName21=digital-audio
LibName22=philips
LibName23=display
LibName24=cypress
LibName25=siliconi
LibName26=opto
LibName27=atmel
LibName28=contrib
LibName29=valves
LibName30=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Amplifier_Audio
LibName31=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Amplifier_Buffer
LibName32=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Amplifier_Current
LibName33=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Amplifier_Difference
LibName34=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Amplifier_Instrumentation
LibName35=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Amplifier_Operational
LibName36=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Amplifier_Video
LibName37=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Analog_ADC
LibName38=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Analog_DAC
LibName39=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Analog_Switch
LibName40=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Analog
LibName41=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Audio
LibName42=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Battery_Management
LibName43=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Comparator
LibName44=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Connector_Generic_Shielded
LibName45=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Connector_Generic
LibName46=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Connector_Specialized
LibName47=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Converter_ACDC
LibName48=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Converter_DCDC
LibName49=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/CPLD_Altera
LibName50=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/CPLD_Xilinx
LibName51=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/CPU_NXP_6800
LibName52=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/CPU_NXP_68000
LibName53=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/CPU_PowerPC
LibName54=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/CPU
LibName55=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Device
LibName56=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Diode_Bridge
LibName57=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Diode_Laser
LibName58=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Diode
LibName59=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Display_Character
LibName60=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Display_Graphic
LibName61=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Driver_Display
LibName62=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Driver_FET
LibName63=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Driver_LED
LibName64=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Driver_Motor
LibName65=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Driver_Relay
LibName66=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/DSP_Freescale
LibName67=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/DSP_Microchip_DSPIC33
LibName68=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/DSP_Motorola
LibName69=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/DSP_Texas
LibName70=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/FPGA_Actel
LibName71=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/FPGA_Xilinx_Artix7
LibName72=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/FPGA_Xilinx_Kintex7
LibName73=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/FPGA_Xilinx_Spartan6
LibName74=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/FPGA_Xilinx_Virtex5
LibName75=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/FPGA_Xilinx_Virtex6
LibName76=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/FPGA_Xilinx_Virtex7
LibName77=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/FPGA_Xilinx
LibName78=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/GPU
LibName79=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Graphic
LibName80=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Interface_CAN_LIN
LibName81=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Interface_CurrentLoop
LibName82=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Interface_Ethernet
LibName83=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Interface_Expansion
LibName84=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Interface_HID
LibName85=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Interface_LineDriver
LibName86=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Interface_Optical
LibName87=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Interface_Telecom
LibName88=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Interface_UART
LibName89=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Interface_USB
LibName90=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Interface
LibName91=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Isolator_Analog
LibName92=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Isolator
LibName93=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Jumper
LibName94=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/LED
LibName95=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Logic_74xgxx
LibName96=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Logic_74xx
LibName97=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Logic_CMOS_4000
LibName98=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Logic_CMOS_IEEE
LibName99=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Logic_LevelTranslator
LibName100=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Logic_Programmable
LibName101=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Logic_TTL_IEEE
LibName102=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/MCU_AnalogDevices
LibName103=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/MCU_Atmel_8051
LibName104=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/MCU_Atmel_ATMEGA
LibName105=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/MCU_Atmel_ATTINY
LibName106=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/MCU_Atmel_AVR
LibName107=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/MCU_Cypress
LibName108=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/MCU_Infineon
LibName109=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/MCU_Intel
LibName110=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/MCU_Microchip_PIC10
LibName111=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/MCU_Microchip_PIC12
LibName112=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/MCU_Microchip_PIC16
LibName113=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/MCU_Microchip_PIC18
LibName114=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/MCU_Microchip_PIC24
LibName115=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/MCU_Microchip_PIC32
LibName116=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/MCU_Microchip_SAME
LibName117=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/MCU_Microchip_SAML
LibName118=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/MCU_Module
LibName119=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/MCU_NXP_ColdFire
LibName120=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/MCU_NXP_HC11
LibName121=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/MCU_NXP_HC12
LibName122=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/MCU_NXP_HCS12
LibName123=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/MCU_NXP_Kinetis
LibName124=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/MCU_NXP_LPC
LibName125=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/MCU_NXP_MAC7100
LibName126=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/MCU_NXP_MCore
LibName127=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/MCU_NXP_S08
LibName128=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/MCU_Parallax
LibName129=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/MCU_SiFive
LibName130=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/MCU_SiliconLabs
LibName131=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/MCU_ST_STM8
LibName132=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/MCU_ST_STM32
LibName133=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/MCU_Texas_MSP430
LibName134=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/MCU_Texas
LibName135=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Mechanical
LibName136=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Memory_Controller
LibName137=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Memory_EEPROM
LibName138=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Memory_Flash
LibName139=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Memory_NVRAM
LibName140=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Memory_RAM
LibName141=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Memory_ROM
LibName142=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Memory_UniqueID
LibName143=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Motor
LibName144=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Oscillator
LibName145=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Potentiometer_Digital
LibName146=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Power_Management
LibName147=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Power_Protection
LibName148=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Power_Supervisor
LibName149=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/power
LibName150=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/pspice
LibName151=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Reference_Current
LibName152=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Reference_Voltage
LibName153=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Regulator_Controller
LibName154=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Regulator_Current
LibName155=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Regulator_Linear
LibName156=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Regulator_SwitchedCapacitor
LibName157=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Regulator_Switching
LibName158=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Relay_SolidState
LibName159=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Relay
LibName160=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/RF_AM_FM
LibName161=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/RF_Bluetooth
LibName162=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/RF_GPS
LibName163=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/RF_Mixer
LibName164=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/RF_Module
LibName165=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/RF_RFID
LibName166=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/RF_WiFi
LibName167=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/RF_ZigBee
LibName168=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/RF
LibName169=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Sensor_Audio
LibName170=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Sensor_Current
LibName171=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Sensor_Gas
LibName172=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Sensor_Humidity
LibName173=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Sensor_Magnetic
LibName174=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Sensor_Motion
LibName175=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Sensor_Optical
LibName176=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Sensor_Pressure
LibName177=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Sensor_Proximity
LibName178=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Sensor_Temperature
LibName179=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Sensor_Touch
LibName180=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Sensor_Voltage
LibName181=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Sensor
LibName182=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Switch
LibName183=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Timer_PLL
LibName184=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Timer_RTC
LibName185=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Timer
LibName186=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Transformer
LibName187=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Transistor_Array
LibName188=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Transistor_BJT
LibName189=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Transistor_FET
LibName190=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Transistor_IGBT
LibName191=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Triac_Thyristor
LibName192=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Valve
LibName193=/Users/Peter/Desktop/Car Project/KicadLibrary/kicad-symbols/Video
